# Generated by Django 6.0.1 on 2026-01-29 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('task_name', models.CharField(max_length=255)),
                ('to_do', models.BooleanField(default=False)),
                ('doing', models.BooleanField(default=False)),
                ('is_done', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('project_name', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=100)),
                ('focus', models.CharField(help_text='The primary area of focus', max_length=200)),
                ('activity', models.CharField(max_length=200)),
                ('pai_actions_overnight', models.TextField(verbose_name='PAI Actions Overnight')),
                ('your_focus_today', models.TextField(verbose_name='Your Focus Today')),
                ('query_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Project Statuses',
            },
        ),
    ]
