# Generated by Django 6.0.1 on 2026-01-29 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('curriculum', '0001_initial'),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='curriculum_capsule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='curriculum.curriculumcapsule'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='portfolio_capsule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='portfolio.portfoliocapsule'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='project_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='core.projectstatus'),
        ),
    ]
