# Generated by Django 6.0.1 on 2026-01-23 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=100)),
                ('focus', models.CharField(help_text='The primary area of focus', max_length=200)),
                ('activity', models.CharField(max_length=200)),
                ('pai_actions_overnight', models.TextField(verbose_name='PAI Actions Overnight')),
                ('your_focus_today', models.TextField(verbose_name='Your Focus Today')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('query_count', models.IntegerField(default=0)),
            ],
        ),
    ]
