# Generated by Django 6.0.1 on 2026-01-26 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas_app', '0002_alter_projectstatus_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumCapsule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capsules', to='atlas_app.projectstatus')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='atlas_app.projectstatus')),
            ],
        ),
    ]
