# Generated by Django 6.0.1 on 2026-01-26 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas_app', '0003_curriculumcapsule_portfolioproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('to_do', models.BooleanField(default=False)),
                ('doing', models.BooleanField(default=False)),
                ('is_done', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('curriculum_capsule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='atlas_app.curriculumcapsule')),
                ('portfolio_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='atlas_app.portfolioproject')),
                ('project_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='atlas_app.projectstatus')),
            ],
        ),
    ]
