# Generated by Django 6.0.1 on 2026-01-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas_app', '0004_checklist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectstatus',
            options={'verbose_name_plural': 'Project Statuses'},
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='repo_url',
            field=models.URLField(blank=True),
        ),
    ]
