# Generated by Django 6.0.1 on 2026-01-26 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas_app', '0005_alter_projectstatus_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curriculumcapsule',
            options={'verbose_name_plural': 'Curriculum Capsules'},
        ),
        migrations.CreateModel(
            name='CurriculumCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='atlas_app.projectstatus')),
            ],
            options={
                'verbose_name_plural': 'Curriculum Courses',
            },
        ),
        migrations.CreateModel(
            name='CurriculumModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='atlas_app.curriculumcourse')),
            ],
        ),
        migrations.CreateModel(
            name='CurriculumLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.IntegerField()),
                ('duration', models.CharField(max_length=10)),
                ('is_completed', models.BooleanField(default=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='atlas_app.curriculummodule')),
            ],
        ),
    ]
