# Generated by Django 6.0.1 on 2026-01-26 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atlas_app', '0006_alter_curriculumcapsule_options_curriculumcourse_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curriculumcourse',
            old_name='name',
            new_name='title',
        ),
    ]
