# Generated by Django 6.0.1 on 2026-01-26 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atlas_app', '0007_rename_name_curriculumcourse_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curriculummodule',
            old_name='module_name',
            new_name='title',
        ),
    ]
