# Generated by Django 6.0.1 on 2026-01-26 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas_app', '0008_rename_module_name_curriculummodule_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumcourse',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
