# Generated by Django 6.0.1 on 2026-01-27 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas_app', '0009_alter_curriculumcourse_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumcourse',
            name='capsule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='atlas_app.curriculumcapsule'),
        ),
        migrations.AlterField(
            model_name='curriculumcourse',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detailed_courses', to='atlas_app.projectstatus'),
        ),
    ]
