# Generated by Django 6.0.1 on 2026-01-27 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas_app', '0010_curriculumcourse_capsule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioMockup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='portfolio_project',
        ),
        migrations.AlterField(
            model_name='curriculumcapsule',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curriculum_capsules', to='atlas_app.projectstatus'),
        ),
        migrations.CreateModel(
            name='PortfolioCapsule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('repo_url', models.URLField(blank=True)),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_capsule_status', to='atlas_app.projectstatus')),
                ('mockups', models.ManyToManyField(blank=True, related_name='portfolio_capsules', to='atlas_app.portfoliomockup')),
            ],
        ),
        migrations.AddField(
            model_name='checklist',
            name='portfolio_capsule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='atlas_app.portfoliocapsule'),
        ),
        migrations.DeleteModel(
            name='PortfolioProject',
        ),
    ]
