# Generated by Django 6.0.1 on 2026-01-27 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas_app', '0011_portfoliomockup_remove_checklist_portfolio_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliomockup',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_mockups', to='atlas_app.projectstatus'),
        ),
    ]
