# Generated by Django 6.0.1 on 2026-01-29 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas_app', '0012_portfoliomockup_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklist',
            options={'verbose_name': 'Checklist', 'verbose_name_plural': 'Checklists'},
        ),
        migrations.AlterModelOptions(
            name='curriculumcapsule',
            options={'verbose_name': 'Curriculum Capsule', 'verbose_name_plural': 'Curriculum Capsules'},
        ),
        migrations.AlterModelOptions(
            name='curriculumcourse',
            options={'verbose_name': 'Curriculum Course', 'verbose_name_plural': 'Curriculum Courses'},
        ),
        migrations.AlterModelOptions(
            name='curriculumlesson',
            options={'verbose_name': 'Curriculum Lesson', 'verbose_name_plural': 'Curriculum Lessons'},
        ),
        migrations.AlterModelOptions(
            name='curriculummodule',
            options={'verbose_name': 'Curriculum Module', 'verbose_name_plural': 'Curriculum Modules'},
        ),
        migrations.AlterModelOptions(
            name='portfoliocapsule',
            options={'verbose_name': 'Portfolio Capsule', 'verbose_name_plural': 'Portfolio Capsules'},
        ),
        migrations.AlterModelOptions(
            name='portfoliomockup',
            options={'verbose_name': 'Portfolio Mockup', 'verbose_name_plural': 'Portfolio Mockups'},
        ),
        migrations.AlterModelOptions(
            name='projectstatus',
            options={'verbose_name': 'Project Status', 'verbose_name_plural': 'Project Statuses'},
        ),
        migrations.AlterField(
            model_name='checklist',
            name='curriculum_capsule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='atlas_app.curriculumcapsule', verbose_name='curriculum capsule'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='doing',
            field=models.BooleanField(default=False, verbose_name='doing'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='is done'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='last updated'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='portfolio_capsule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='atlas_app.portfoliocapsule', verbose_name='portfolio capsule'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='project_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='atlas_app.projectstatus', verbose_name='project status'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='task_name',
            field=models.CharField(max_length=255, verbose_name='task name'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='to_do',
            field=models.BooleanField(default=False, verbose_name='to do'),
        ),
        migrations.AlterField(
            model_name='curriculumcapsule',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='last updated'),
        ),
        migrations.AlterField(
            model_name='curriculumcapsule',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curriculum_capsules', to='atlas_app.projectstatus', verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='curriculumcapsule',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='curriculumcourse',
            name='capsule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='atlas_app.curriculumcapsule', verbose_name='capsule'),
        ),
        migrations.AlterField(
            model_name='curriculumcourse',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='last updated'),
        ),
        migrations.AlterField(
            model_name='curriculumcourse',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detailed_courses', to='atlas_app.projectstatus', verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='curriculumcourse',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='curriculumlesson',
            name='duration',
            field=models.CharField(max_length=10, verbose_name='duration'),
        ),
        migrations.AlterField(
            model_name='curriculumlesson',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='is completed'),
        ),
        migrations.AlterField(
            model_name='curriculumlesson',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='atlas_app.curriculummodule', verbose_name='module'),
        ),
        migrations.AlterField(
            model_name='curriculumlesson',
            name='order',
            field=models.IntegerField(verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='curriculumlesson',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='curriculummodule',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='atlas_app.curriculumcourse', verbose_name='course'),
        ),
        migrations.AlterField(
            model_name='curriculummodule',
            name='order',
            field=models.IntegerField(default=1, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='curriculummodule',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='portfoliocapsule',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='last updated'),
        ),
        migrations.AlterField(
            model_name='portfoliocapsule',
            name='mockups',
            field=models.ManyToManyField(blank=True, related_name='portfolio_capsules', to='atlas_app.portfoliomockup', verbose_name='mockups'),
        ),
        migrations.AlterField(
            model_name='portfoliocapsule',
            name='repo_url',
            field=models.URLField(blank=True, verbose_name='repository URL'),
        ),
        migrations.AlterField(
            model_name='portfoliocapsule',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='portfoliomockup',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='portfoliomockup',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='last updated'),
        ),
        migrations.AlterField(
            model_name='portfoliomockup',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_mockups', to='atlas_app.projectstatus', verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='portfoliomockup',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='projectstatus',
            name='activity',
            field=models.CharField(max_length=200, verbose_name='activity'),
        ),
        migrations.AlterField(
            model_name='projectstatus',
            name='focus',
            field=models.CharField(help_text='The primary area of focus', max_length=200, verbose_name='focus'),
        ),
        migrations.AlterField(
            model_name='projectstatus',
            name='project_name',
            field=models.CharField(max_length=200, verbose_name='project name'),
        ),
        migrations.AlterField(
            model_name='projectstatus',
            name='query_count',
            field=models.IntegerField(default=0, verbose_name='query count'),
        ),
        migrations.AlterField(
            model_name='projectstatus',
            name='status',
            field=models.CharField(max_length=100, verbose_name='status'),
        ),
    ]
